[tool.poetry]
authors = ["Tomas Beuzen"]
description = "Calculate word counts in a text file!"
license = "MIT"
name = "pycounts-daoming123"
readme = "README.md"
version = "0.1.0"

# 1. packages 自己占一块，括号要及时关上
packages = [
  {include = "pycounts", from = "src"},
]

# 2. include 也要独立出来，不要写在 packages 的括号里
include = ["tests/*", "CHANGELOG.md"]

[tool.poetry.dependencies]
matplotlib = ">=3.10"
python = "^3.12"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[dependency-groups]
dev = [
  "pytest (>=9.0.2,<10.0.0)",
  "pytest-cov (>=7.0.0,<8.0.0)",
  "myst-nb (>=1.4.0,<2.0.0) ; python_version >= \"3.9\" and python_version < \"4.0\"",
  "sphinx-autoapi (>=3.8.0,<4.0.0)",
  "sphinx-rtd-theme (>=3.1.0,<4.0.0)",
  "jupyter (>=1.1.1,<2.0.0)",
  "jupyter-book (>=2.1.2,<3.0.0)",
  "python-semantic-release (>=10.5.3,<11.0.0)",
]
[tool.semantic_release]
version_variable = "pyproject.toml:version"
